export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'dashboard',
    path: '/dashboard',
    title: '仪表盘',
    requires_auth: true,
    icon: 'icon-park-outline:analysis',
    menu_type: 'directory',
    component_path: null,
    id: '1',
    order: 0,
    parent_id: null,
  },
  {
    name: 'workbench',
    path: '/dashboard/workbench',
    title: '工作台',
    requires_auth: true,
    icon: 'icon-park-outline:alarm',
    pin_tab: true,
    menu_type: 'page',
    component_path: '/dashboard/workbench/index.vue',
    id: '2',
    parent_id: null,
  },
  {
    name: 'monitor',
    path: '/dashboard/monitor',
    title: '监控页',
    requires_auth: true,
    icon: 'icon-park-outline:anchor',
    menu_type: 'page',
    component_path: '/dashboard/monitor/index.vue',
    id: '3',
    parent_id: null,
  },

  // {
  //   name: 'setting',
  //   path: '/setting',
  //   title: '系统设置',
  //   requires_auth: true,
  //   icon: 'icon-park-outline:setting',
  //   menu_type: 'directory',
  //   component_path: null,
  //   id: '35',
  //   parent_id: null,
  // },
  // {
  //   name: 'accountSetting',
  //   path: '/setting/account',
  //   title: '用户设置',
  //   requires_auth: true,
  //   icon: 'icon-park-outline:every-user',
  //   menu_type: 'page',
  //   component_path: '/setting/account/index.vue',
  //   id: '36',
  //   parent_id: '35',
  // },
  // {
  //   name: 'roleSetting',
  //   path: '/setting/roles',
  //   title: '角色设置',
  //   requires_auth: true,
  //   icon: 'icon-park-outline:book-one',
  //   component_path: '/setting/roles/index.vue',
  //   id: '41',
  //   parent_id: '35',
  // },

  {
    name: 'userCenter',
    path: '/userCenter',
    title: '个人中心',
    requires_auth: true,
    icon: 'carbon:user-avatar-filled-alt',
    component_path: '/setting/userCenter/index.vue',
    id: '999',
    parent_id: null,
    hidden: true,
  },
  // {
  //   name: 'about',
  //   path: '/about',
  //   title: '关于',
  //   requires_auth: true,
  //   icon: 'icon-park-outline:info',
  //   component_path: '/demo/about/index.vue',
  //   id: '40',
  //   parent_id: null,
  // },
  // {
  //   name: 'systemSetting',
  //   path: '/system',
  //   title: '开发设置',
  //   requires_auth: true,
  //   icon: 'icon-park-outline:setting',
  //   menu_type: 'directory',
  //   component_path: null,
  //   id: '42',
  //   parent_id: null,
  // },
  // {
  //   name: 'dictionarySetting',
  //   path: '/system/dictionary',
  //   title: '字典设置',
  //   requires_auth: true,
  //   icon: 'icon-park-outline:book-one',
  //   component_path: '/system/dictionary/index.vue',
  //   id: '37',
  //   parent_id: '42',
  // },
  // {
  //   name: 'menuSetting',
  //   path: '/system/menu',
  //   title: '菜单设置',
  //   requires_auth: true,
  //   icon: 'icon-park-outline:application-menu',
  //   component_path: '/system/menu/index.vue',
  //   id: '38',
  //   parent_id: '42',
  // },

]
